# Generated by Django 5.2.14 on 2026-05-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactMlScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField(blank=True, null=True)),
                ('company_name', models.TextField(blank=True, null=True)),
                ('sector', models.TextField(blank=True, null=True)),
                ('sales', models.FloatField(blank=True, null=True)),
                ('net_profit', models.FloatField(blank=True, null=True)),
                ('operating_profit', models.FloatField(blank=True, null=True)),
                ('opm_percentage', models.FloatField(blank=True, null=True)),
                ('debt_to_equity', models.FloatField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('health_label', models.TextField(blank=True, null=True)),
                ('fiscal_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_ml_scores',
                'managed': False,
            },
        ),
    ]
